function data = getDataPoly(phenotypes,imgDir,resolution,trainPerc)
%GETDATAPOLY Summary of this function goes here
%   Detailed explanation goes here
system(['rm -rf ' imgDir '/*']);
writePhenoToDisk(phenotypes,imgDir);

dataDir = [imgDir '/'];
imds = imageDatastore(dataDir, ...
    'IncludeSubfolders',false, ...
    'LabelSource','foldernames');

[ds1,ds2] = splitEachLabel(imds,trainPerc,'randomized');

augmenter = imageDataAugmenter( ...
    'FillValue', 0);

%augmenter = imageDataAugmenter( ...
%    'RandRotation', [0 180], ...
%    'RandXScale',[0.1 2], ...
%    'RandYScale',[0.1 2], ...
%    'RandXTranslation',[-0.5 0.5], ...
%    'RandYTranslation',[-0.5 0.5], ...
%    'FillValue', 0);

data.trainStore = augmentedImageDatastore([resolution resolution],ds1,'DataAugmentation',augmenter);
data.testStore = augmentedImageDatastore([resolution resolution],ds2);
end

